<?php
/**
 * @file
 * initial_migration.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function initial_migration_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "feeds" && $api == "feeds_importer_default") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_views_api().
 */
function initial_migration_views_api() {
  list($module, $api) = func_get_args();
  if ($module == "views" && $api == "views_default") {
    return array("version" => "3.0");
  }
}

/**
 * Implements hook_node_info().
 */
function initial_migration_node_info() {
  $items = array(
    'blind_configuration' => array(
      'name' => t('Blind configuration'),
      'base' => 'node_content',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Name'),
      'help' => '',
    ),
    'fabric' => array(
      'name' => t('Product'),
      'base' => 'node_content',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Friendly name'),
      'help' => '',
    ),
  );
  return $items;
}
